---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: doges.app.demo
spec:
  group: app.demo
  names:
    kind: Doge
    plural: doges
    singular: doge
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                image:
                  description: Image of Doge
                  nullable: true
                  type: string
                number:
                  description: magic number
                  type: integer
                dogeStatus:
                  description: Status of Doge
                  type: string
              required:
                - number
                - dogeStatus
              type: object
          required:
            - spec
          title: Doge
          type: object
      served: true
      storage: true
      subresources: {}
