{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admission-webhook.webhook.fullname" . }}
  labels:
    {{- include "admission-webhook.webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "admission-webhook.webhook.selectorLabels" . | nindent 6 }}
  {{- with .Values.webhook.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (printf "%s/webhook/configmap.yaml" .Template.BasePath) . | sha256sum }}
      {{- with .Values.webhook.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "admission-webhook.webhook.selectorLabels" . | nindent 8 }}
      {{- with .Values.webhook.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "admission-webhook.webhook.serviceAccountName" . }}
      containers:
        - name: app
          {{- with .Values.webhook.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ printf "%s/%s:%s" (include "admission-webhook.webhook.image.registry" .) .Values.webhook.image.repository  (include "admission-webhook.webhook.image.tag" .) }}
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          command:
            - admission-webhook
          args:
            - run
          env:
            {{- include "admission-webhook.podInfoEnvs" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "admission-webhook.webhook.fullname" . }}
          volumeMounts:
              - name: webhook-certificate
                mountPath: "/certs"
                readOnly: true
          ports:
            - name: https
              containerPort: {{ include "admission-webhook.webhook.httpPort" . }}
              protocol: TCP
          {{- with .Values.webhook.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: webhook-certificate
          secret:
            secretName: {{ .Values.certificate.secretName }}
            optional: false
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}