{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admission-webhook.webhook.fullname" . }}
  labels:
    {{- include "admission-webhook.webhook.labels" . | nindent 4 }}
  {{- with .Values.webhook.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      appProtocol: https
      targetPort: https
  selector:
    {{- include "admission-webhook.webhook.selectorLabels" . | nindent 4 }}
{{- end }}