{{- if and .Values.webhook.enabled .Values.webhook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "admission-webhook.webhook.serviceAccountName" . }}
  labels:
    {{- include "admission-webhook.webhook.labels" . | nindent 4 }}
  {{- with .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.webhook.serviceAccount.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}