---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-demo
  annotations:
    cert-manager.io/inject-ca-from: admission-webhook/admission-webhook-crt
webhooks:
  - name: foo-admission.default.svc
    # Optionally restrict events from namespaces with a specific label.
    # namespaceSelector:
    #   matchLabels:
    #     some-label: "true"
    clientConfig:
      #caBundle: "${CA_PEM_B64}"
      #url: "https://${PRIVATE_IP}:8443/mutate"
      # For controllers behind k8s services, use the format below instead of a url
      service:
       name: admission-webhook
       namespace: admission-webhook
       path: "/api/v1/admission/mutate"
       port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: ["app.demo"]
        apiVersions: ["v1alpha1"]
        resources: ["doges"]
    failurePolicy: Fail
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5