#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

if type uname >/dev/null 2>&1; then
  KERNEL=$(uname -s | tr "[:upper:]" "[:lower:]")
else
  error "uname not found, failed to detect operating system."
  exit 1
fi

if [[ $KERNEL == "linux" ]]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  case "$ID" in
  nixos)
    warn "Dependencies is provided by nix-shell"
    ;;
  debian | ubuntu | devuan | elementary)

    apt-get update
    apt-get install --no-install-recommends -y \
      unzip \
      ssh-client \
      ca-certificates \
      libgnutls30 \
      build-essential \
      cmake \
      binutils \
      libprotobuf-dev \
      pkg-config \
      libssl-dev \
      unixodbc-dev \
      curl \
      gnupg2 \
      perl \
      file

    ;;

  *)
    error "Linux $ID is unknown, dependencies will have to be installed manually."
    exit 1
    ;;
  esac
else
  error "$KERNEL is unknown, dependencies will have to be installed manually."
  exit 1
fi
