apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  dnsNames:
  - "{{ include "admission-webhook.webhook.fullname" . }}.{{ .Release.Namespace }}.svc"
  - "{{ include "admission-webhook.webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    name: {{ .Values.certificate.issuerName }}