pub const API_ADDRESS: &str = "ADMISSION_WEBHOOK_API_ADDRESS";
pub const API_PORT: &str = "ADMISSION_WEBHOOK_API_PORT";

pub const TLS_CERT: &str = "ADMISSION_WEBHOOK_TLS_CERT";
pub const TLS_KEY: &str = "ADMISSION_WEBHOOK_TLS_KEY";

pub const DOGE_DEFAULT_IMAGE: &str = "ADMISSION_WEBHOOK_DOGE_DEFAULT_IMAGE";
pub const DOGE_DEFAULT_NUMBER: &str = "ADMISSION_WEBHOOK_DOGE_DEFAULT_NUMBER";
pub const DOGE_DEFAULT_STATUS: &str = "ADMISSION_WEBHOOK_DOGE_DEFAULT_STATUS";

pub const TELEMETRY_OTLP_ENDPOINT: &str = "ADMISSION_WEBHOOK_TELEMETRY_OTLP_ENDPOINT";
